name: projectroot
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Bibliotecas utilizadas no projeto
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  signature: ^5.5.0 # Adicionando a dependência para assinatura digital

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
