name: projectroot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies: # Consolidando todas as dependências em uma única seção
  flutter:
    sdk: flutter

  # Adicionando bibliotecas usadas no projeto
  fl_chart: ^0.70.2 # Certifique-se de usar a versão mais recente
  cupertino_icons: ^1.0.8

dev_dependencies: # Dependências de desenvolvimento
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true